"""empty message

Revision ID: b81d18047a80
Revises: 6db5fe3ff87c
Create Date: 2023-04-16 15:22:13.581132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81d18047a80'
down_revision = '6db5fe3ff87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
